# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'deletedialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DeleteDialog(object):
    signal = None

    def __init__(self, _signal: list):
        self.signal = _signal

    def setupUi(self, DeleteDialog):
        DeleteDialog.setObjectName("DeleteDialog")
        DeleteDialog.resize(368, 163)
        self.verticalLayout = QtWidgets.QVBoxLayout(DeleteDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelMessage = QtWidgets.QLabel(DeleteDialog)
        self.labelMessage.setAlignment(QtCore.Qt.AlignCenter)
        self.labelMessage.setObjectName("labelMessage")
        self.verticalLayout.addWidget(self.labelMessage)
        self.labelFilename = QtWidgets.QLabel(DeleteDialog)
        self.labelFilename.setAlignment(QtCore.Qt.AlignCenter)
        self.labelFilename.setObjectName("labelFilename")
        self.verticalLayout.addWidget(self.labelFilename)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ConfirmBtn = QtWidgets.QPushButton(DeleteDialog)
        self.ConfirmBtn.setObjectName("ConfirmBtn")
        self.horizontalLayout.addWidget(self.ConfirmBtn)
        self.DenyBtn = QtWidgets.QPushButton(DeleteDialog)
        self.DenyBtn.setObjectName("DenyBtn")
        self.horizontalLayout.addWidget(self.DenyBtn)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(DeleteDialog)
        QtCore.QMetaObject.connectSlotsByName(DeleteDialog)

        # 按鍵功能綁定
        self.ConfirmBtn.clicked.connect(lambda: self.update_and_exit(1, DeleteDialog))
        self.DenyBtn.clicked.connect(lambda: self.update_and_exit(2, DeleteDialog))

    def retranslateUi(self, DeleteDialog):
        _translate = QtCore.QCoreApplication.translate
        DeleteDialog.setWindowTitle(_translate("DeleteDialog", "Dialog"))
        self.labelMessage.setText(_translate("DeleteDialog", "Are you sure you want to permanently delete this file?"))
        self.labelFilename.setText(_translate("DeleteDialog", "?"))
        self.ConfirmBtn.setText(_translate("DeleteDialog", "Yes"))
        self.DenyBtn.setText(_translate("DeleteDialog", "No"))

    def update_and_exit(self, _signal: int, Dialog):
        self.signal.append(_signal)
        Dialog.close()

# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     DeleteDialog = QtWidgets.QDialog()
#     ui = Ui_DeleteDialog()
#     ui.setupUi(DeleteDialog)
#     DeleteDialog.show()
#     sys.exit(app.exec_())
