# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'opening.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LaunchWindow(object):
    def setupUi(self, LaunchWindow):
        LaunchWindow.setObjectName("LaunchWindow")
        LaunchWindow.resize(400, 300)
        self.gridLayout = QtWidgets.QGridLayout(LaunchWindow)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(LaunchWindow)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(LaunchWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(LaunchWindow)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 1, 0, 1, 1)

        self.retranslateUi(LaunchWindow)
        QtCore.QMetaObject.connectSlotsByName(LaunchWindow)
        print('Launching window set')

    def retranslateUi(self, LaunchWindow):
        _translate = QtCore.QCoreApplication.translate
        LaunchWindow.setWindowTitle(_translate("LaunchWindow", "Launching Mask Editor"))
        self.label.setText(_translate("LaunchWindow", "MASK  EDITOR"))
        self.label_2.setText(_translate("LaunchWindow", "Opening editor..."))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     LaunchWindow = QtWidgets.QDialog()
#     ui = Ui_LaunchWindow()
#     ui.setupUi(LaunchWindow)
#     LaunchWindow.show()
#     sys.exit(app.exec_())
