# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lineeditdialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogLineEdit(object):
    def setupUi(self, DialogLineEdit):
        DialogLineEdit.setObjectName("DialogLineEdit")
        DialogLineEdit.resize(302, 165)
        self.verticalLayout = QtWidgets.QVBoxLayout(DialogLineEdit)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(DialogLineEdit)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(DialogLineEdit)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.buttonBox = QtWidgets.QDialogButtonBox(DialogLineEdit)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(DialogLineEdit)
        self.buttonBox.accepted.connect(DialogLineEdit.accept)
        self.buttonBox.rejected.connect(DialogLineEdit.reject)
        QtCore.QMetaObject.connectSlotsByName(DialogLineEdit)

    def retranslateUi(self, DialogLineEdit):
        _translate = QtCore.QCoreApplication.translate
        DialogLineEdit.setWindowTitle(_translate("DialogLineEdit", "DialogLineEdit"))
        self.label.setText(_translate("DialogLineEdit", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DialogLineEdit = QtWidgets.QDialog()
    ui = Ui_DialogLineEdit()
    ui.setupUi(DialogLineEdit)
    DialogLineEdit.show()
    sys.exit(app.exec_())
