# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'savedialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SaveDialog(object):
    signal = None

    def __init__(self, _signal: list):
        self.signal = _signal

    def setupUi(self, SaveDialog):
        SaveDialog.setObjectName("SaveDialog")
        SaveDialog.resize(317, 163)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(SaveDialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.labelMessage = QtWidgets.QLabel(SaveDialog)
        self.labelMessage.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelMessage.setAlignment(QtCore.Qt.AlignCenter)
        self.labelMessage.setObjectName("labelMessage")
        self.verticalLayout_2.addWidget(self.labelMessage)
        self.labelYesMsg = QtWidgets.QLabel(SaveDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelYesMsg.sizePolicy().hasHeightForWidth())
        self.labelYesMsg.setSizePolicy(sizePolicy)
        self.labelYesMsg.setIndent(50)
        self.labelYesMsg.setObjectName("labelYesMsg")
        self.verticalLayout_2.addWidget(self.labelYesMsg)
        self.labelNoMsg = QtWidgets.QLabel(SaveDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelNoMsg.sizePolicy().hasHeightForWidth())
        self.labelNoMsg.setSizePolicy(sizePolicy)
        self.labelNoMsg.setIndent(50)
        self.labelNoMsg.setObjectName("labelNoMsg")
        self.verticalLayout_2.addWidget(self.labelNoMsg)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ConfirmBtn = QtWidgets.QPushButton(SaveDialog)
        self.ConfirmBtn.setObjectName("ConfirmBtn")
        self.horizontalLayout.addWidget(self.ConfirmBtn)
        self.DenyBtn = QtWidgets.QPushButton(SaveDialog)
        self.DenyBtn.setObjectName("DenyBtn")
        self.horizontalLayout.addWidget(self.DenyBtn)
        self.CancelBtn = QtWidgets.QPushButton(SaveDialog)
        self.CancelBtn.setObjectName("CancelBtn")
        self.horizontalLayout.addWidget(self.CancelBtn)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(SaveDialog)
        QtCore.QMetaObject.connectSlotsByName(SaveDialog)

        # 按鍵功能綁定
        self.ConfirmBtn.clicked.connect(lambda: self.update_and_exit(1, SaveDialog))
        self.DenyBtn.clicked.connect(lambda: self.update_and_exit(2, SaveDialog))
        self.CancelBtn.clicked.connect(lambda: self.update_and_exit(3, SaveDialog))

    def retranslateUi(self, SaveDialog):
        _translate = QtCore.QCoreApplication.translate
        SaveDialog.setWindowTitle(_translate("SaveDialog", "Save changes?"))
        self.labelMessage.setText(_translate("SaveDialog", "Would you like to save your changes?"))
        self.labelYesMsg.setText(_translate("SaveDialog", "[Yes] saves your changes"))
        self.labelNoMsg.setText(_translate("SaveDialog", "[No] discards your changes"))
        self.ConfirmBtn.setText(_translate("SaveDialog", "Yes"))
        self.DenyBtn.setText(_translate("SaveDialog", "No"))
        self.CancelBtn.setText(_translate("SaveDialog", "Cancel"))

    def update_and_exit(self, _signal: int, SaveDialog):
        self.signal.append(_signal)
        SaveDialog.close()


